global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'substation1'
    static_configs:
      - targets: ['substation1:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'substation2'
    static_configs:
      - targets: ['substation2:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'substation3'
    static_configs:
      - targets: ['substation3:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s